### ISSUE TITLE
drawPixel() doesn't work after setRotation()

### ISSUE THREAD

**Issue by funnypolynomial** [Smoke-And-Wires/TFT-Shield-Example-Code#1]
drawPixel() alters its behaviour based on the rotation data member.  But if you've called SWTFT::setRotation() the hardware is already dealing with it, so it's applied "twice".  The rendering gets messed up; pixels pile up on the edges.

**Comment by NickTG** [comment]
Thanks for picking that up.

The hardware rotation settings should only be relevant when you are writing to consecutive DRAM addresses. According to the datasheet they are intended to allow areas of the screen to be filled by just sending a stream of image data , and the addresses should be incremented automatically in the direction specified by three bits in the entry mode register (0x0003)

drawPixel() specifies the x,y location of each pixel and needs to convert the coordinates back to the native (rotation = 0) values before writing them to the screen.
.
I'm not sure why the Memory access controls aren't working as I expected, but until I figure them out I have commented out that part of the code.
