### ISSUE TITLE
tftpaint doesn't compile

### ISSUE THREAD

**Issue by beamzer** [Smoke-And-Wires/TFT-Shield-Example-Code#2]
The three of the four examples work (great, many thanks!) , but tftpaint does not compile :-(
Below is the compiler output. Hope you can help.

thanks,
Ewald....

Arduino: 1.0.6 + Td: 1.20-rc5 (Mac OS X), Board: "Arduino Uno"

/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=106 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants/standard -I/Applications/Arduino.app/Contents/Resources/Java/libraries/Adafruit_GFX -I/Applications/Arduino.app/Contents/Resources/Java/libraries/SWTFT-Shield /var/folders/0c/_9w2vr0d66737wxd8vb_l4ph0000gn/T/build7722940267231770035.tmp/tftpaint.cpp -o /var/folders/0c/_9w2vr0d66737wxd8vb_l4ph0000gn/T/build7722940267231770035.tmp/tftpaint.cpp.o 
tftpaint.ino:5:25: warning: TouchScreen.h: No such file or directory
tftpaint:23: error: 'TouchScreen' does not name a type
tftpaint.ino: In function 'void setup()':
tftpaint.ino:46: warning: only initialized variables can be placed into program memory area
tftpaint.ino:52: warning: only initialized variables can be placed into program memory area
tftpaint.ino: In function 'void loop()':
tftpaint:84: error: 'TSPoint' was not declared in this scope
tftpaint:84: error: expected `;' before 'p'
tftpaint:96: error: 'p' was not declared in this scope
tftpaint.ino:140: warning: comparison between signed and unsigned integer expressions
tftpaint.ino:141: warning: comparison between signed and unsigned integer expressions
tftpaint.ino:145: warning: comparison between signed and unsigned integer expressions

**Comment by beamzer** [comment]
Ah, i found you blog which belongs to this code:
http://www.smokeandwires.co.nz/blog/a-2-4-tft-touchscreen-shield-for-arduino/
and already resolved the issue,
i needed https://github.com/adafruit/Touch-Screen-Library
and now it's functioning fine.

thanks!
Ewald...

**Comment by Puneethsvj** [comment]
I used tft,  from robokit it was 240×340 resolution. But it not supports some of libraries.. I need to work this tft for hotel menu order displaying purpose. Please tell me what libraries i have to use.
